import type { LucideIcon } from 'lucide-react';
import type { ConfigType } from '@/api/configApi';
import {
  Building2,
  MapPin,
  Monitor,
  FileText,
  Percent,
  ClipboardList,
  Grid3X3,
  ChefHat,
  UtensilsCrossed,
  Boxes,
  Printer,
  Wallet,
  TicketPercent,
  Users,
  QrCode,
  Bell,
  Shield,
  Receipt,
  Clock,
  Settings,
} from 'lucide-react';

export type ConfigSectionDef = {
  id: ConfigType | 'branch' | 'users' | 'hub';
  path: string;
  label: string;
  description: string;
  icon: LucideIcon;
  group: string;
  /** Maps to ConfigType for JSON configs; null for entity-managed sections */
  configType: ConfigType | null;
};

export const CONFIG_SECTIONS: ConfigSectionDef[] = [
  {
    id: 'hub',
    path: '/admin/configuration',
    label: 'Overview',
    description: 'All POS configuration at a glance',
    icon: Settings,
    group: 'Overview',
    configType: null,
  },
  {
    id: 'restaurant',
    path: '/admin/configuration/restaurant',
    label: 'Restaurant',
    description: 'Profile, GSTIN, FSSAI, branding used on invoices & QR',
    icon: Building2,
    group: 'Organization',
    configType: 'restaurant',
  },
  {
    id: 'branch',
    path: '/admin/configuration/branch',
    label: 'Branch / Outlet',
    description: 'Multi-outlet setup affecting POS, inventory & reports',
    icon: MapPin,
    group: 'Organization',
    configType: null,
  },
  {
    id: 'pos',
    path: '/admin/configuration/pos',
    label: 'POS Settings',
    description: 'Order types, cart behavior, numbering prefixes',
    icon: Monitor,
    group: 'Operations',
    configType: 'pos',
  },
  {
    id: 'order',
    path: '/admin/configuration/order',
    label: 'Order Settings',
    description: 'Min order, delivery/packaging charges, auto-accept',
    icon: ClipboardList,
    group: 'Operations',
    configType: 'order',
  },
  {
    id: 'table',
    path: '/admin/configuration/table',
    label: 'Table Management',
    description: 'Floors, capacities, table status rules',
    icon: Grid3X3,
    group: 'Operations',
    configType: 'table',
  },
  {
    id: 'kot',
    path: '/admin/configuration/kot',
    label: 'KOT / Kitchen',
    description: 'Kitchen tickets, stations & print routing',
    icon: ChefHat,
    group: 'Operations',
    configType: 'kot',
  },
  {
    id: 'billing',
    path: '/admin/configuration/billing',
    label: 'Billing & Invoice',
    description: 'Invoice format, footer, tax breakup display',
    icon: FileText,
    group: 'Finance',
    configType: 'billing',
  },
  {
    id: 'tax',
    path: '/admin/configuration/tax',
    label: 'Tax & GST',
    description: 'GST rates, inclusive/exclusive pricing',
    icon: Percent,
    group: 'Finance',
    configType: 'tax',
  },
  {
    id: 'payment',
    path: '/admin/configuration/payment',
    label: 'Payment Methods',
    description: 'Cash, UPI, card — shown dynamically in POS checkout',
    icon: Wallet,
    group: 'Finance',
    configType: 'payment',
  },
  {
    id: 'discount',
    path: '/admin/configuration/discount',
    label: 'Discounts & Offers',
    description: 'Percent/fixed discounts with permission gates',
    icon: TicketPercent,
    group: 'Finance',
    configType: 'discount',
  },
  {
    id: 'receipt',
    path: '/admin/configuration/receipt',
    label: 'Receipt Settings',
    description: 'Live receipt preview for thermal printers',
    icon: Receipt,
    group: 'Finance',
    configType: 'receipt',
  },
  {
    id: 'menu',
    path: '/admin/configuration/menu',
    label: 'Menu & Pricing',
    description: 'Variants, channels, kitchen routing preferences',
    icon: UtensilsCrossed,
    group: 'Catalog',
    configType: 'menu',
  },
  {
    id: 'inventory',
    path: '/admin/configuration/inventory',
    label: 'Inventory',
    description: 'Units, reorder levels, auto-deduction rules',
    icon: Boxes,
    group: 'Catalog',
    configType: 'inventory',
  },
  {
    id: 'customer',
    path: '/admin/configuration/customer',
    label: 'Customer Settings',
    description: 'Phone required, loyalty, GST on customers',
    icon: Users,
    group: 'Guests',
    configType: 'customer',
  },
  {
    id: 'qr',
    path: '/admin/configuration/qr',
    label: 'QR Ordering',
    description: 'Table QR → Menu → Order → KOT → Billing',
    icon: QrCode,
    group: 'Guests',
    configType: 'qr',
  },
  {
    id: 'printer',
    path: '/admin/configuration/printer',
    label: 'Printers',
    description: 'Receipt & KOT printers with test print',
    icon: Printer,
    group: 'Hardware',
    configType: 'printer',
  },
  {
    id: 'business_hours',
    path: '/admin/configuration/business-hours',
    label: 'Business Hours',
    description: 'Per-day hours that POS can respect',
    icon: Clock,
    group: 'Hardware',
    configType: 'business_hours',
  },
  {
    id: 'notifications',
    path: '/admin/configuration/notifications',
    label: 'Notifications',
    description: 'SMS, email, WhatsApp & order alerts',
    icon: Bell,
    group: 'System',
    configType: 'notifications',
  },
  {
    id: 'users',
    path: '/admin/configuration/users',
    label: 'User & Role Access',
    description: 'RBAC for POS actions and configuration',
    icon: Shield,
    group: 'System',
    configType: null,
  },
  {
    id: 'general',
    path: '/admin/configuration/general',
    label: 'General Preferences',
    description: 'Language, theme, session timeout',
    icon: Settings,
    group: 'System',
    configType: 'general',
  },
];

export function getConfigSection(id: string): ConfigSectionDef | undefined {
  return CONFIG_SECTIONS.find((s) => s.id === id || s.path.endsWith(`/${id}`));
}
