import {
  Building2,
  CreditCard,
  Crown,
  FileText,
  TrendingUp,
  Headphones,
  TicketPercent,
  Tag,
  Globe,
  Megaphone,
  Settings,
  Percent,
  Wallet,
  Flag,
  ScrollText,
  Shield,
  Monitor,
  Layers,
  PackagePlus,
  Gift,
  Warehouse,
  ShoppingCart,
  Truck,
  Banknote,
  CalendarCheck,
  UserCheck,
  WalletCards,
  Heart,
  Star,
  Printer,
  Bell,
  Undo2,
  MapPin,
  BarChart3,
} from 'lucide-react';
import type { ModuleDefinition } from '@/pages/modules/GenericModulePage';

export const MODULE_DEFINITIONS: Record<string, ModuleDefinition> = {
  pos: { title: 'POS Billing', description: 'In-store point of sale for quick order entry and billing.', icon: Monitor, status: 'coming_soon', features: ['Quick billing', 'Split payments', 'Receipt print', 'Table assignment'] },
  variants: { title: 'Variants', description: 'Manage item size, spice level, and custom variants.', icon: Layers, status: 'coming_soon', features: ['Variant groups', 'Price modifiers', 'Default selection'] },
  addons: { title: 'Addons', description: 'Extra toppings and add-on items for menu customization.', icon: PackagePlus, status: 'coming_soon', features: ['Addon groups', 'Mandatory rules', 'Max selection'] },
  combos: { title: 'Combos', description: 'Meal combos and bundled offers.', icon: Gift, status: 'coming_soon', features: ['Combo builder', 'Discount rules', 'Item bundling'] },
  stock: { title: 'Stock Management', description: 'Real-time stock levels and alerts.', icon: Warehouse, status: 'beta', features: ['Stock alerts', 'Batch tracking', 'Expiry management'], columns: ['Item', 'Quantity', 'Unit', 'Status'], sampleRows: [['Tomatoes', '45', 'kg', 'In Stock'], ['Chicken', '12', 'kg', 'Low Stock']] },
  purchase: { title: 'Purchase Orders', description: 'Create and track purchase orders.', icon: ShoppingCart, status: 'coming_soon', features: ['PO creation', 'Approval workflow', 'GRN entry'] },
  suppliers: { title: 'Suppliers', description: 'Supplier directory and purchase history.', icon: Truck, status: 'coming_soon', features: ['Supplier profiles', 'Payment terms', 'Purchase history'] },
  expenses: { title: 'Expenses', description: 'Track operational expenses and approvals.', icon: Banknote, status: 'coming_soon', features: ['Expense categories', 'Approval flow', 'Receipt upload'] },
  reservations: { title: 'Reservations', description: 'Table reservations and guest management.', icon: CalendarCheck, status: 'coming_soon', features: ['Online booking', 'Table assignment', 'SMS reminders'] },
  takeaway: { title: 'Take Away', description: 'Take-away order management.', icon: ShoppingCart, status: 'coming_soon', features: ['Counter pickup', 'Order queue', 'Token numbers'] },
  attendance: { title: 'Attendance', description: 'Staff clock-in/out and shift tracking.', icon: UserCheck, status: 'coming_soon', features: ['Clock in/out', 'Shift roster', 'Export reports'] },
  payroll: { title: 'Payroll', description: 'Staff salary and payroll management.', icon: WalletCards, status: 'coming_soon', features: ['Salary slips', 'Deductions', 'Payment history'] },
  analytics: { title: 'Analytics', description: 'Advanced business analytics and insights.', icon: TrendingUp, status: 'coming_soon', features: ['Revenue trends', 'Customer insights', 'Peak hours'] },
  offers: { title: 'Offers', description: 'Promotional offers and campaigns.', icon: TicketPercent, status: 'coming_soon', features: ['Happy hours', 'BOGO deals', 'Minimum order rules'] },
  coupons: { title: 'Coupons', description: 'Discount coupons and promo codes.', icon: Tag, status: 'coming_soon', features: ['Coupon codes', 'Usage limits', 'Validity periods'] },
  loyalty: { title: 'Loyalty Program', description: 'Customer loyalty points and rewards.', icon: Heart, status: 'coming_soon', features: ['Points earning', 'Redemption rules', 'Tier levels'] },
  wallet: { title: 'Wallet', description: 'Customer wallet and prepaid balance.', icon: Wallet, status: 'coming_soon', features: ['Top-up', 'Cashback', 'Transaction history'] },
  membership: { title: 'Membership', description: 'Membership plans and subscriptions.', icon: Crown, status: 'coming_soon', features: ['Plan tiers', 'Member benefits', 'Renewals'] },
  reviews: { title: 'Reviews', description: 'Customer ratings and feedback.', icon: Star, status: 'coming_soon', features: ['Star ratings', 'Review moderation', 'Response management'] },
  settings: { title: 'Settings', description: 'Restaurant profile and configuration.', icon: Settings, status: 'beta', features: ['Business hours', 'Theme', 'Language', 'Notifications'] },
  printer: { title: 'Printer Setup', description: 'Configure KOT and receipt printers.', icon: Printer, status: 'coming_soon', features: ['KOT printer', 'Bill printer', 'Auto-print rules'] },
  taxes: { title: 'Tax Configuration', description: 'GST and tax settings.', icon: Percent, status: 'coming_soon', features: ['GST rates', 'HSN codes', 'Tax inclusive/exclusive'] },
  notifications: { title: 'Notifications', description: 'SMS, email, and push notification settings.', icon: Bell, status: 'coming_soon', features: ['SMS templates', 'Email templates', 'WhatsApp alerts'] },
  refunds: { title: 'Refunds & Returns', description: 'Process refunds and returns.', icon: Undo2, status: 'coming_soon', features: ['Partial refunds', 'Credit notes', 'Return reasons'] },
  invoices: { title: 'Invoices', description: 'Generate and manage customer invoices.', icon: FileText, status: 'coming_soon', features: ['Invoice generation', 'PDF export', 'Email delivery'] },
  'audit-logs': { title: 'Audit Logs', description: 'Track all system changes and user actions.', icon: ScrollText, status: 'coming_soon', features: ['Change tracking', 'User activity', 'Export logs'] },
  branches: { title: 'Branches', description: 'Multi-branch management.', icon: MapPin, status: 'live', features: ['Branch profiles', 'Hours', 'Payment setup'] },
  reports: { title: 'Reports', description: 'Sales, GST, and business reports.', icon: BarChart3, status: 'beta', features: ['Sales reports', 'GST reports', 'P&L statements'] },
  // Super Admin modules
  'super-restaurants': { title: 'Restaurants', description: 'Manage all tenant restaurants.', icon: Building2, status: 'live', features: ['Onboarding', 'Status control', 'Module toggles'], columns: ['Restaurant', 'Plan', 'Status', 'Revenue'], sampleRows: [['Spice Garden', 'Pro', 'Active', '₹2.4L'], ['Urban Bites', 'Starter', 'Active', '₹85K']] },
  'super-subscriptions': { title: 'Subscriptions', description: 'Tenant subscription management.', icon: CreditCard, status: 'beta', features: ['Renewals', 'Upgrades', 'Billing cycles'] },
  'super-plans': { title: 'Plans', description: 'Subscription plan tiers and pricing.', icon: Crown, status: 'beta', features: ['Plan builder', 'Feature limits', 'Pricing tiers'] },
  'super-invoices': { title: 'Platform Invoices', description: 'SaaS billing invoices for tenants.', icon: FileText, status: 'coming_soon', features: ['Auto billing', 'Invoice history', 'Payment tracking'] },
  'super-revenue': { title: 'Revenue Analytics', description: 'Platform-wide revenue and growth metrics.', icon: TrendingUp, status: 'beta', features: ['MRR/ARR', 'Churn analysis', 'Growth charts'] },
  'super-tickets': { title: 'Support Tickets', description: 'Customer support ticket management.', icon: Headphones, status: 'coming_soon', features: ['Ticket queue', 'Priority levels', 'SLA tracking'] },
  'super-coupons': { title: 'Platform Coupons', description: 'Global coupon management.', icon: TicketPercent, status: 'coming_soon', features: ['Global promos', 'Tenant coupons', 'Usage analytics'] },
  'super-promo': { title: 'Promo Codes', description: 'Promotional code management.', icon: Tag, status: 'coming_soon', features: ['Code generation', 'Redemption tracking', 'Campaign links'] },
  'super-cms': { title: 'CMS', description: 'Content management for landing pages.', icon: Globe, status: 'coming_soon', features: ['Page builder', 'Blog posts', 'SEO settings'] },
  'super-announcements': { title: 'Announcements', description: 'Platform-wide announcements.', icon: Megaphone, status: 'coming_soon', features: ['Banner alerts', 'In-app notices', 'Scheduled posts'] },
  'super-settings': { title: 'System Settings', description: 'Global platform configuration.', icon: Settings, status: 'coming_soon', features: ['Platform config', 'Email settings', 'Maintenance mode'] },
  'super-taxes': { title: 'Global Taxes', description: 'Default tax templates for new tenants.', icon: Percent, status: 'coming_soon', features: ['Tax templates', 'Country presets', 'GST defaults'] },
  'super-payment': { title: 'Payment Gateway', description: 'Platform payment gateway configuration.', icon: Wallet, status: 'coming_soon', features: ['Razorpay', 'Stripe', 'UPI config'] },
  'super-features': { title: 'Feature Flags', description: 'Toggle features across the platform.', icon: Flag, status: 'coming_soon', features: ['Feature toggles', 'A/B testing', 'Rollout control'] },
  'super-audit': { title: 'Audit Logs', description: 'Platform-wide audit trail.', icon: ScrollText, status: 'coming_soon', features: ['Admin actions', 'Security events', 'Compliance export'] },
  'super-roles': { title: 'Role Permissions', description: 'Global role and permission management.', icon: Shield, status: 'coming_soon', features: ['Role builder', 'Permission matrix', 'Default roles'] },
};

export function getModuleDefinition(key: string): ModuleDefinition | undefined {
  return MODULE_DEFINITIONS[key];
}
